# Generated by Django 6.0.5 on 2026-06-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anno',
            field=models.CharField(max_length=12),
        ),
    ]
