# Generated by Django 6.0.5 on 2026-06-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_libro_anno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anno',
            field=models.IntegerField(),
        ),
    ]
